import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="/styles/test.scss" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main classNameName={styles.main}>
        <Link href="/test">test </Link>
        <button className="govuk-button" data-module="govuk-button">
          Save and continue
        </button>
      </main>
    </>
  );
}
